### ISSUE TITLE
docker间怎么依赖呢

### ISSUE THREAD

**Issue by ysicing** [leoChaoGlut/spring-cloud-demo#1]
Rt.我将每个服务build成docker镜像，可以提供一下config-repo的样式么。config_server

**Comment by leoChaoGlut** [comment]
你好,没看懂你的问题,能否描述清楚些?
每个服务的配置,可以像下面这样:
spring:
--application:
----name: service-0 #服务注册成功后,会到配置中心查找 service-0.yml,并读取到服务,缓存到内存.`
  cloud:
--config:
----discovery:
------enabled: true
------service-id: config-center # 配置中心的spring.application.name 
eureka:
--client:
----serviceUrl:
------defaultZone: http://ipOrHostname:port/eureka/ #注册中心的url

每一个docker container只要能正常访问到'注册中心'和'配置中心',就可以正常注册和获取配置.
config-repo可以使用纯文件方式,或者使用git来管理配置文件. 如果使用git,新增的配置文件需要先add & commit,然后才能通过配置中心正常访问到.

**Comment by ysicing** [comment]
额，不好意思，之前没接触过spring cloud。，我在研究研究
